extends SceneTree

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var packed: PackedScene = load("res://Player.tscn")
	var preview: PlayerVisual = packed.instantiate()
	assert(preview.get_node("VisualRoot/Body").sprite_frames != null)
	assert(preview.get_node("VisualRoot/Helmet").texture != null)
	assert(preview.get_node("VisualRoot/WeaponPivot/Weapon").texture != null)
	assert(preview.get_node("VisualRoot/GuardField").visible == false)
	root.add_child(preview)
	await process_frame
	assert(preview.body.animation == &"idle")
	assert(preview.body.frame == 0)
	for anim in [&"idle", &"run", &"jump", &"slide", &"death"]:
		assert(preview.body.sprite_frames.has_animation(anim))
		assert(preview.body.sprite_frames.get_frame_count(anim) == (10 if anim == &"run" else 8))
	assert(preview.body.sprite_frames.get_animation_loop(&"run"))
	assert(not preview.body.sprite_frames.get_animation_loop(&"death"))
	assert(preview.standing_shape.size == Vector2(38, 92))
	assert(preview.slide_shape.size == Vector2(54, 36))
	assert(preview.hurtbox_rect() == Rect2(Vector2(-19, -92), Vector2(38, 92)))
	preview.set_motion(false, false, 0, Vector2(400, -100), true, true)
	assert(preview.solid_collision.shape == preview.standing_shape)
	assert(preview.guard_effect.visible)
	assert(preview.muzzle_world_position() == preview.muzzle.global_position)
	preview.body_state = "run"
	for frame in range(10):
		preview.body_time = (float(frame) + 0.1) / 14.0
		preview._apply_frames()
		assert(preview.body.frame == frame)
		var source_column: int = PlayerVisual.RUN_FRAME_ORDER[frame]
		assert(preview.body.sprite_frames.get_frame_texture(&"run", frame).region.position.x == source_column * 256)
		assert(preview.body.position.y == 128 - PlayerVisual.RUN_CONTACT_BASELINES[source_column])
		assert(preview.front_pivot.position == Vector2(PlayerVisual.SOCKET_X[1][source_column] - 128, PlayerVisual.SOCKET_TOP[1][source_column] + 30 - PlayerVisual.RUN_CONTACT_BASELINES[source_column]))
	assert(preview.solid_collision.shape == preview.standing_shape)
	preview.set_collision_pose(true)
	assert(preview.hurtbox_rect() == Rect2(Vector2(-27, -36), Vector2(54, 36)))
	assert(preview.solid_collision.position == preview.hurt_collision.position)
	preview.play_death()
	assert(preview.solid_collision.disabled and preview.hurt_collision.disabled)
	assert(not preview.helmet.visible and not preview.front_arm.visible and not preview.back_arm.visible)
	preview.body_time = 3.0
	preview._apply_frames()
	assert(preview.body.frame == 7)
	preview.free()

	var game: Node2D = load("res://main.tscn").instantiate()
	root.add_child(game)
	await process_frame
	var visual: PlayerVisual = game.get_node("Player")
	assert(game.get_children().filter(func(child: Node) -> bool: return child is PlayerVisual).size() == 1)
	assert(game.state == "playing")
	assert(game._player_hitbox() == Rect2(Vector2(171, 540), Vector2(38, 92)))
	assert(visual.body.sprite_frames.get_frame_texture(&"run", 0).atlas.resource_path == "res://body(2).png")
	assert(visual.visual_root.scale == Vector2(0.5, 0.5))
	assert(visual.helmet.texture.resource_path == "res://helmet_game.png")
	assert(visual.front_arm.texture.resource_path == "res://low_ap_fire_3x2.png")
	for layer_name in ["Background", "MiddleLayer", "Track"]:
		var layer: Parallax2D = game.get_node(layer_name)
		assert(layer.repeat_size == Vector2(3344, 0))
		assert(layer.get_node("Image").texture.get_size() == Vector2(1672, 941))
		assert(layer.get_node("Mirror").flip_h)
	assert(not game.has_node("BackgroundMoon"))
	assert(game.get_node("Ground/CollisionShape2D").shape.size == Vector2(960, 200))
	assert(game.get_node("Ground/CollisionShape2D").position == Vector2(480, 732))
	game.distance = 200.0
	game._update_parallax()
	assert(game.get_node("Background").scroll_offset.x == -30.0)
	assert(game.get_node("MiddleLayer").scroll_offset.x == -110.0)
	assert(game.get_node("Track").scroll_offset.x == -200.0)
	game.crouching = true
	visual.set_collision_pose(true)
	game.obstacles.clear()
	game.obstacles.append({"x": 190.0, "rect": Rect2(-15, -100, 30, 40), "danger": true})
	assert(not game._can_stand())
	game._update_player(0.0)
	assert(game.crouching)
	assert(game._player_hitbox() == Rect2(Vector2(163, 596), Vector2(54, 36)))
	game.obstacles.clear()
	game._update_player(0.0)
	assert(not game.crouching)
	assert(game._player_hitbox() == Rect2(Vector2(171, 540), Vector2(38, 92)))
	Input.action_press("crouch")
	game._update_player(0.1)
	assert(game.crouching and game.slide_time_left > 0.0)
	Input.action_release("crouch")
	game._update_player(0.2)
	assert(game.crouching and visual.solid_collision.shape == visual.slide_shape)
	game._update_player(0.5)
	assert(not game.crouching and visual.solid_collision.shape == visual.standing_shape)
	game._die("test")
	assert(visual.solid_collision.disabled and visual.hurt_collision.disabled)
	assert(visual.body.animation == &"death")
	print("PLAYER SCENE / COLLISION SMOKE: PASS")
	quit(0)
